output_dir: ~/scratch/torchprotein_output/

datasets:
  - class: Fluorescence
    path: ~/scratch/protein-datasets/
    atom_feature: null
    bond_feature: null
    transform:
      class: Compose
      transforms:
        - class: ProteinView
          view: "residue"
  - class: Stability
    path: ~/scratch/protein-datasets/
    atom_feature: null
    bond_feature: null
    center: True
    transform:
      class: Compose
      transforms:
        - class: ProteinView
          view: "residue"

tasks:
  - class: PropertyPrediction
    criterion: mse
    metric: [ "mae", "rmse", "spearmanr" ]
    normalization: False
    num_mlp_layer: 2
    hidden_dims: [1024]
    conv_output: False
  - class: PropertyPrediction
    criterion: mse
    metric: ["mae", "rmse", "spearmanr"]
    normalization: False
    num_mlp_layer: 2
    hidden_dims: [1024]
    conv_output: False

model:
  class: ProteinHybridNetwork
  model1:
    class: ProteinConvolutionalNetwork
    input_dim: 21
    hidden_dims: [1024, 1024]
    kernel_size: 5
    padding: 2
  model2:
    class: ProtBert
    path: ~/scratch/protbert-model-weights/

eval_metric: Center - Stability spearmanr

optimizer:
  class: Adam
  lr: 2.0e-5

engine:
  gpus: [0, 1]
  batch_size: 16

train:
  num_epoch: 100
  tradeoff: 1.0