output_dir: ~/scratch/torchprotein_output/

dataset:
  class: SecondaryStructure
  path: ~/scratch/protein-datasets/
  atom_feature: null
  bond_feature: null
  transform:
    class: Compose
    transforms:
      - class: ProteinView
        view: "residue"

test_split: cb513

task:
  class: NodePropertyPrediction
  model:
    class: ProteinHybridNetwork
    model1:
      class: ProteinConvolutionalNetwork
      input_dim: 21
      hidden_dims: [1024, 1024]
      kernel_size: 5
      padding: 2
    model2:
      class: ProtBert
      path: ~/scratch/protbert-model-weights/
  criterion: ce
  metric: ["micro_acc", "macro_acc"]
  num_mlp_layer: 2
  num_class: 3

eval_metric: macro_acc

optimizer:
  class: Adam
  lr: 2.0e-4

engine:
  gpus: [0, 1, 2]
  # gpus: [0]
  batch_size: 1

train:
  num_epoch: 100
