output_dir: ~/scratch/torchprotein_output/

datasets:
  - class: Fluorescence
    path: ~/scratch/protein-datasets/
    atom_feature: null
    bond_feature: null
    transform:
      class: Compose
      transforms:
        - class: ProteinView
          view: "residue"
  - class: SecondaryStructure
    path: ~/scratch/protein-datasets/
    atom_feature: null
    bond_feature: null
    test_split: cb513
    transform:
      class: Compose
      transforms:
        - class: TruncateProtein
          max_length: 200
          random: True
        - class: ProteinView
          view: "residue"

tasks:
  - class: PropertyPrediction
    criterion: mse
    metric: [ "mae", "rmse", "spearmanr" ]
    normalization: False
    num_mlp_layer: 2
  - class: NodePropertyPrediction
    criterion: ce
    metric: [ "micro_acc", "macro_acc" ]
    num_mlp_layer: 2
    num_class: 3

model:
  class: ProtBert
  path: ~/scratch/protbert-model-weights/

eval_metric: Center - Fluorescence spearmanr

# checkpoint: /mnt/sda/2022-0526/home/wxpan/scratch/torchprotein_output/MultitaskLearning/Fluorescence_SecondaryStructure/ProteinHybridNetwork_2023-09-26-15-17-22/model_epoch_60.pth

optimizer:
  class: Adam
  lr: 2.0e-5

engine:
  gpus: [0, 1]
  batch_size: 16

train:
  num_epoch: 60
  tradeoff: 1.0