output_dir: ~/scratch/torchprotein_output/

datasets:
  - class: Stability
    path: ~/scratch/protein-datasets/
    atom_feature: null
    bond_feature: null
    center: True
    transform:
      class: Compose
      transforms:
        - class: ProteinView
          view: "residue"
  - class: SecondaryStructure
    path: ~/scratch/protein-datasets/
    atom_feature: null
    bond_feature: null
    test_split: cb513
    transform:
      class: Compose
      transforms:
        - class: TruncateProtein
          max_length: 200
          random: True
        - class: ProteinView
          view: "residue"

tasks:
  - class: PropertyPrediction
    criterion: mse
    metric: [ "mae", "rmse", "spearmanr" ]
    normalization: False
    num_mlp_layer: 2
    hidden_dims: [1024, 256, 64]
    conv_output: True
  - class: NodePropertyPrediction
    criterion: ce
    metric: [ "micro_acc", "macro_acc" ]
    num_mlp_layer: 2
    num_class: 3

model:
  class: ProteinHybridNetwork
  model1:
    class: ProteinConvolutionalNetwork
    input_dim: 21
    hidden_dims: [1024, 1024]
    kernel_size: 5
    padding: 2
  model2:
    class: ProtBert
    path: ~/scratch/protbert-model-weights/

eval_metric: Center - Stability spearmanr

checkpoint: /mnt/sda/2022-0526/home/wxpan/protein/best_params/stability/stability_conv_4mlp.pth

optimizer:
  class: Adam
  lr: 2.0e-5

engine:
  gpus: [0, 1]
  batch_size: 32

train:
  num_epoch: 60
  tradeoff: 1.0